### ISSUE TITLE
Publishing arcamens is illegal

### ISSUE THREAD

**Issue by vporton** [arcamens/arcamens#1]
Publishing arcamens is illegal because I hold the copyright for a part of the code. The code must be not used and removed.

**Comment by iogf** [comment]
Your copyright is regarding django-debits. I was going to give you 50% of the percent. You threatened me to steal the copyright. You know more than anyone that i conceived and designed arcamens entirely. 

You helped along dialogs and discussing features.  I told you several times to stop your insanities towards me. You made me afraid of just stealing the whole copyright.

I suggest you to work with me on arcamens as an open source project i have given you credits about financing also regarding specification details. 

In case someone doubts about you having active participation in the technical details of arcamens also considerable activity in the designing of it. I ask them to compare your actual open source profile.

https://github.com/vporton

with mine.
https://github.com/iogf

If it remains doubts i'll point to the forums where you claim to be the winner of the mathematical prize abel and others!

If you insist in claiming copyright and playing the victim role i'm gonna host all the dialogs of us where you say i should obey you otherwise i would be fired of a company that i have idealized and developed all the projects. I can prove www.arcamens.com was purchased by me initially it was on my godaddy account. You have paid to keep the domain on though you can stay with it at all since you paid for it when i had no money.

I unfortunately fell into your trip about having money to support arcamens. I was stupid and too much of a good person to insist working with you. You helped me with some amount monthly to keep working on arcamens because you had plans to just trick me. 

I have old code of arcamens at bitbucket where it shows you have no commits at all. There is also gitlab commits in case you didn't fake it. Just in the hypothesis of you insisting to claim copyright of something that you wouldn't be able to conceive even if you lived 300 years more.

I'm not sure if your behavior is due to your not having mental meds properly lately. I'm really sorry but i couldn't stand for the risk of you stealing the work of 3 years. 

To those who are interested i have just left Victor Porton with the code of another project management platform to pay the help that he has given me along 7 months. It is named splittask.

The next time someone offers you help to hunt your lunch and you aren't really able to help at all but the person just shares it then you should just be thankful.

Again, i told you to stop your delirious behavior. I offer you the opportunity to in fact CONTRIBUTE to arcamens. Actually we can discuss a way of making money out of it through email or hangouts, maybe slack?

**Comment by iogf** [comment]
To those who may read this conversation. Here it shows Victor Porton
demanding the abel prize.

http://www.mathematics21.org/abel-prize.html

The guy who writes code like this https://github.com/vporton/django-debits/blob/master/debits/paypal/views.py

Should he really get the abel prize as well as get partial copyright on arcamens code? Huh.

**Comment by iogf** [comment]
As a proof that victor porton as participation just on spec discussion and feedback here it goes. 

https://bitbucket.org/arcamens/

Arcamens was originally on bitbucket. I own both accouts the Arcamens Softwares also the one whose commits are made and my name shows up.

**Comment by vporton** [comment]
As a  result of iogf's stupidity, the original repository was deleted.

It _did_ contain my commits. For one example, I wrote the system of uploading files to Amazon S3 under secret keys. I did also many other changes.

iogf seems to ignore that if a software project contains even one change of another person, it can't be published open source without his agreement. But now iogf ignores whether his acts are legal and whether they are reasonable.
